apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    io.kompose.service: scheduler
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
        - args:
            - scheduler
          env:
            - name: EXECUTOR
              value: Celery
            - name: FERNET_KEY
              value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - name: LOAD_EX
              value: "n"
          image: ' '
          name: scheduler
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/airflow/dags
              name: scheduler-claim0
      restartPolicy: Always
      volumes:
        - name: scheduler-claim0
          persistentVolumeClaim:
            claimName: scheduler-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - scheduler
        from:
          kind: ImageStreamTag
          name: scheduler:1.10.9
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
